name: Build the game

on:
  push:
    branches: [master-dev]
  workflow_dispatch:
jobs:

  BuildMobileCache:
    name: Build Caches
    permissions: write-all
    uses: ./.github/workflows/dependencies.yml
    with:
      os: macos-15
      CACHE_NAME: P-Slice.1.0.mobile-cache
      setupScript: sh ./setup/mobile.sh

  BuildAndroid:
    permissions: write-all
    needs: BuildMobileCache
    name: Build Android
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      name: Android
      os: ubuntu-24.04
      buildArgs: "android"
      exportPath: android
      artifactName: P-Slice.1.0.android
      cacheLibrariesPath: P-Slice.1.0.mobile-cache
      artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
      cachePath: P-Slice.1.0.build-android
